#general settings
logging: true
mail:
  enabled: true
  from: andresmontanez@gmail.com
  password: xxxxxx
  smtp: smtp.gmail.com
  to:
    - andresmontanez@gmail.com
    - andres.montanez@zenreworks.com

