magephp:
#    composer:
#        path: composer
#    symfony:
#        console: bin/console
#    log_dir: app/logs
    environments:
        production:
            user: root
#            ssh:
#                port: 22
#                flags: -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
            branch: test
            host_path: /var/www/test
            releases: 4
            exclude:
                - vendor
                - app/cache
                - app/log
                - web/app_dev.php
            hosts:
                - webserver1
                - webserver2
                - webserver3
            pre-deploy:
                - git/update
#                - composer/install #: { flags: '--optimize' }
#                - composer/generate-autoload
            on-deploy:
#                - symfony/cache-clear: { env: 'dev' }
#                - symfony/cache-warmup: { env: 'dev' }
#                - symfony/assets-install: { env: 'dev' }
#                - symfony/assetic-dump: { env: 'dev' }
            on-release:
            post-release:
            post-deploy:
