#production
deployment:
  user: root
  from: ./
  to: /var/www/vhosts/example.com/www
  excludes:
    - application/data/cache/twig/*
releases:
  enabled: true
  symlink: current
  directory: releases
  tasks:
hosts:
  - s01.example.com
  - s02.example.com
  - s03.example.com
  - s05.example.com
tasks:
  pre-deploy:
    - scm/update
  on-deploy:
    - deployment/rsync
    - privileges
  #post-deploy: