#production
deployment:
  user: root
#  from: ./
  source:
    type: git
    repository: git://github.com/andres-montanez/Zend-Framework-Twig-example-app.git
    from: production
    temporal: /tmp/myAppClone
  to: /var/www/vhosts/example.com/www
  excludes:
    - application/data/cache/twig/*
releases:
  enabled: true
  max: 5
  symlink: current
  directory: releases
hosts:
  - s01.example.com:22
  - s02.example.com
tasks:
  pre-deploy:
    - scm/update
  on-deploy:
    - privileges
    - sampleTask
    - sampleTaskRollbackAware
  #post-deploy: