#staging
deployment:
  user: root
  from: ./
  to: /var/www/vhosts/example.com/staging
#hosts: /tmp/current-staging-hosts.txt
hosts:
  - s01.example.com:22
  - s02.example.com
tasks:
  pre-deploy:
    - scm/update
  on-deploy:
    - privileges
    - sampleTask
    - sampleTaskRollbackAware
  #post-deploy: