#staging
deployment:
  user: stg_user
  from: ./
  to: /var/www/vhosts/example.com/staging
hosts:
  - staging.example.com
tasks:
  pre-deploy:
    - scm/update
  on-deploy:
    - deployment/rsync
    - privileges
  #post-deploy: