#staging
deployment:
  user: root
  from: ./
  to: /var/www/
releases:
  enabled: true
  max: 5
  symlink: current
  directory: releases
hosts:
  - localhost
tasks:
  pre-deploy:
    - scm/update
  on-deploy:
    - privileges
    - sampleTask
    - sampleTaskRollbackAware
  #post-release
  #post-deploy:
