#staging
deployment:
  user: root
  from: ./
  to: /var/www/
releases:
  enabled: true
  max: 5
  symlink: current
  directory: releases
hosts:
  - localhost
  - dbserver
tasks:
  pre-deploy:
    - sampleTask
#    - scm/update
  on-deploy:
    - privileges
    - sampleTask
    - sampleTaskRollbackAware
    - taskWithParameters:
        booleanOption: true
    - taskWithParameters
  post-release:
#    - sampleTask
  post-deploy:
    - sampleTask
