#staging
deployment:
  user: stg_user
  from: ./
  to: /var/www/vhosts/example.com/staging
hosts: /tmp/current-staging-hosts.txt
tasks:
  pre-deploy:
    - scm/update
  on-deploy:
    - privileges
    - sampleTask
    - sampleTaskRollbackAware
  #post-deploy: